name: CBOM Workflow Summary Action
description: Add a CBOM analysis summary to a workflow run
runs:
  using: composite
  steps:
    - name: Unarchive results
      uses: actions/download-artifact@v4
      with:
        name: cbom-results
        path: ${{ github.workspace }}/cbom-results
    - name: Post summary info
      shell: bash -ex {0}
      continue-on-error: true
      run: |
        # Post summary info to workflow run
        echo "::group::Post summary info to workflow run"
        cd ${{ github.workspace }}/cbom-results
        ls -lah
        echo "| Owner    | Repo    | Commit    | Language    | Result Count    |" >> $GITHUB_STEP_SUMMARY
        echo "|----------|---------|-----------|-------------|-----------------|" >> $GITHUB_STEP_SUMMARY
        shopt -s globstar
        jq -cn 'foreach inputs as $i (0; . +1; "\(input_filename|rtrimstr(".sarif"))/\($i.runs[].results|length)")' **/*.sarif \
        | xargs -I "{}" bash -c 'IFS=/ read -r OWNER REPO COMMIT LANGUAGE RESULT_COUNT <<< {};
            echo "| ${OWNER} | ${REPO} | ${COMMIT} | ${LANGUAGE} | ${RESULT_COUNT} |" >> $GITHUB_STEP_SUMMARY'
        echo "::endgroup::"
